var pages = [{'name': 'object MainGame : Game', 'description':'main.MainGame', 'location':'core/main/-main-game/index.html', 'searchKey':'MainGame'},
{'name': 'open override fun create()', 'description':'main.MainGame.create', 'location':'core/main/-main-game/create.html', 'searchKey':'create'},
{'name': 'open override fun dispose()', 'description':'main.MainGame.dispose', 'location':'core/main/-main-game/dispose.html', 'searchKey':'dispose'},
{'name': 'open override fun dispose()', 'description':'screens.LogoScreen.dispose', 'location':'core/screens/-logo-screen/dispose.html', 'searchKey':'dispose'},
{'name': 'open override fun dispose()', 'description':'screens.QuarryScreen.dispose', 'location':'core/screens/-quarry-screen/dispose.html', 'searchKey':'dispose'},
{'name': 'open override fun dispose()', 'description':'screens.StartingScreen.dispose', 'location':'core/screens/-starting-screen/dispose.html', 'searchKey':'dispose'},
{'name': 'open override fun dispose()', 'description':'screens.TownScreen.dispose', 'location':'core/screens/-town-screen/dispose.html', 'searchKey':'dispose'},
{'name': 'open override fun dispose()', 'description':'stages.StartingStage.dispose', 'location':'core/stages/-starting-stage/dispose.html', 'searchKey':'dispose'},
{'name': 'open override fun dispose()', 'description':'stages.TownStage.dispose', 'location':'core/stages/-town-stage/dispose.html', 'searchKey':'dispose'},
{'name': 'class LogoScreen(game: MainGame) : Screen', 'description':'screens.LogoScreen', 'location':'core/screens/-logo-screen/index.html', 'searchKey':'LogoScreen'},
{'name': 'fun LogoScreen(game: MainGame)', 'description':'screens.LogoScreen.LogoScreen', 'location':'core/screens/-logo-screen/-logo-screen.html', 'searchKey':'LogoScreen'},
{'name': 'open override fun hide()', 'description':'screens.LogoScreen.hide', 'location':'core/screens/-logo-screen/hide.html', 'searchKey':'hide'},
{'name': 'open override fun hide()', 'description':'screens.QuarryScreen.hide', 'location':'core/screens/-quarry-screen/hide.html', 'searchKey':'hide'},
{'name': 'open override fun hide()', 'description':'screens.StartingScreen.hide', 'location':'core/screens/-starting-screen/hide.html', 'searchKey':'hide'},
{'name': 'open override fun hide()', 'description':'screens.TownScreen.hide', 'location':'core/screens/-town-screen/hide.html', 'searchKey':'hide'},
{'name': 'open override fun pause()', 'description':'screens.LogoScreen.pause', 'location':'core/screens/-logo-screen/pause.html', 'searchKey':'pause'},
{'name': 'open override fun pause()', 'description':'screens.QuarryScreen.pause', 'location':'core/screens/-quarry-screen/pause.html', 'searchKey':'pause'},
{'name': 'open override fun pause()', 'description':'screens.StartingScreen.pause', 'location':'core/screens/-starting-screen/pause.html', 'searchKey':'pause'},
{'name': 'open override fun pause()', 'description':'screens.TownScreen.pause', 'location':'core/screens/-town-screen/pause.html', 'searchKey':'pause'},
{'name': 'open override fun render(delta: Float)', 'description':'screens.LogoScreen.render', 'location':'core/screens/-logo-screen/render.html', 'searchKey':'render'},
{'name': 'open override fun render(delta: Float)', 'description':'screens.QuarryScreen.render', 'location':'core/screens/-quarry-screen/render.html', 'searchKey':'render'},
{'name': 'open override fun render(delta: Float)', 'description':'screens.StartingScreen.render', 'location':'core/screens/-starting-screen/render.html', 'searchKey':'render'},
{'name': 'open override fun render(delta: Float)', 'description':'screens.TownScreen.render', 'location':'core/screens/-town-screen/render.html', 'searchKey':'render'},
{'name': 'open override fun resize(width: Int, height: Int)', 'description':'screens.LogoScreen.resize', 'location':'core/screens/-logo-screen/resize.html', 'searchKey':'resize'},
{'name': 'open override fun resize(width: Int, height: Int)', 'description':'screens.QuarryScreen.resize', 'location':'core/screens/-quarry-screen/resize.html', 'searchKey':'resize'},
{'name': 'open override fun resize(width: Int, height: Int)', 'description':'screens.StartingScreen.resize', 'location':'core/screens/-starting-screen/resize.html', 'searchKey':'resize'},
{'name': 'open override fun resize(width: Int, height: Int)', 'description':'screens.TownScreen.resize', 'location':'core/screens/-town-screen/resize.html', 'searchKey':'resize'},
{'name': 'open override fun resume()', 'description':'screens.LogoScreen.resume', 'location':'core/screens/-logo-screen/resume.html', 'searchKey':'resume'},
{'name': 'open override fun resume()', 'description':'screens.QuarryScreen.resume', 'location':'core/screens/-quarry-screen/resume.html', 'searchKey':'resume'},
{'name': 'open override fun resume()', 'description':'screens.StartingScreen.resume', 'location':'core/screens/-starting-screen/resume.html', 'searchKey':'resume'},
{'name': 'open override fun resume()', 'description':'screens.TownScreen.resume', 'location':'core/screens/-town-screen/resume.html', 'searchKey':'resume'},
{'name': 'open override fun show()', 'description':'screens.LogoScreen.show', 'location':'core/screens/-logo-screen/show.html', 'searchKey':'show'},
{'name': 'open override fun show()', 'description':'screens.QuarryScreen.show', 'location':'core/screens/-quarry-screen/show.html', 'searchKey':'show'},
{'name': 'open override fun show()', 'description':'screens.StartingScreen.show', 'location':'core/screens/-starting-screen/show.html', 'searchKey':'show'},
{'name': 'open override fun show()', 'description':'screens.TownScreen.show', 'location':'core/screens/-town-screen/show.html', 'searchKey':'show'},
{'name': 'class QuarryScreen(game: MainGame) : Screen', 'description':'screens.QuarryScreen', 'location':'core/screens/-quarry-screen/index.html', 'searchKey':'QuarryScreen'},
{'name': 'fun QuarryScreen(game: MainGame)', 'description':'screens.QuarryScreen.QuarryScreen', 'location':'core/screens/-quarry-screen/-quarry-screen.html', 'searchKey':'QuarryScreen'},
{'name': 'class StartingScreen(game: MainGame) : Screen', 'description':'screens.StartingScreen', 'location':'core/screens/-starting-screen/index.html', 'searchKey':'StartingScreen'},
{'name': 'fun StartingScreen(game: MainGame)', 'description':'screens.StartingScreen.StartingScreen', 'location':'core/screens/-starting-screen/-starting-screen.html', 'searchKey':'StartingScreen'},
{'name': 'class TownScreen(game: MainGame) : Screen', 'description':'screens.TownScreen', 'location':'core/screens/-town-screen/index.html', 'searchKey':'TownScreen'},
{'name': 'fun TownScreen(game: MainGame)', 'description':'screens.TownScreen.TownScreen', 'location':'core/screens/-town-screen/-town-screen.html', 'searchKey':'TownScreen'},
{'name': 'class LabelNotif(str: String, stage: TownStage) : LabelBuilder', 'description':'stages.LabelNotif', 'location':'core/stages/-label-notif/index.html', 'searchKey':'LabelNotif'},
{'name': 'fun LabelNotif(str: String, stage: TownStage)', 'description':'stages.LabelNotif.LabelNotif', 'location':'core/stages/-label-notif/-label-notif.html', 'searchKey':'LabelNotif'},
{'name': 'open override fun draw(batch: Batch?, parentAlpha: Float)', 'description':'stages.LabelNotif.draw', 'location':'core/stages/-label-notif/draw.html', 'searchKey':'draw'},
{'name': 'open override fun draw(batch: Batch?, parentAlpha: Float)', 'description':'stages.LabelStart.draw', 'location':'core/stages/-label-start/draw.html', 'searchKey':'draw'},
{'name': 'open override fun draw()', 'description':'stages.TownStage.draw', 'location':'core/stages/-town-stage/draw.html', 'searchKey':'draw'},
{'name': 'class LabelStart : LabelBuilder', 'description':'stages.LabelStart', 'location':'core/stages/-label-start/index.html', 'searchKey':'LabelStart'},
{'name': 'fun LabelStart()', 'description':'stages.LabelStart.LabelStart', 'location':'core/stages/-label-start/-label-start.html', 'searchKey':'LabelStart'},
{'name': 'class Lvlactor(but: Button, progressBar: ProgressBar) : Group', 'description':'stages.Lvlactor', 'location':'core/stages/-lvlactor/index.html', 'searchKey':'Lvlactor'},
{'name': 'fun Lvlactor(but: Button, progressBar: ProgressBar)', 'description':'stages.Lvlactor.Lvlactor', 'location':'core/stages/-lvlactor/-lvlactor.html', 'searchKey':'Lvlactor'},
{'name': 'class StartingStage(v: Viewport, batch: SpriteBatch) : Stage', 'description':'stages.StartingStage', 'location':'core/stages/-starting-stage/index.html', 'searchKey':'StartingStage'},
{'name': 'fun StartingStage(v: Viewport, batch: SpriteBatch)', 'description':'stages.StartingStage.StartingStage', 'location':'core/stages/-starting-stage/-starting-stage.html', 'searchKey':'StartingStage'},
{'name': 'class TownStage(v: Viewport, game: MainGame) : Stage', 'description':'stages.TownStage', 'location':'core/stages/-town-stage/index.html', 'searchKey':'TownStage'},
{'name': 'fun TownStage(v: Viewport, game: MainGame)', 'description':'stages.TownStage.TownStage', 'location':'core/stages/-town-stage/-town-stage.html', 'searchKey':'TownStage'},
{'name': 'fun ground(): Image', 'description':'stages.TownStage.ground', 'location':'core/stages/-town-stage/ground.html', 'searchKey':'ground'},
{'name': 'open class LabelBuilder(colorF: Color, sizeF: Float, text: String, xT: Float, yT: Float) : Label', 'description':'utils.LabelBuilder', 'location':'core/utils/-label-builder/index.html', 'searchKey':'LabelBuilder'},
{'name': 'fun LabelBuilder(colorF: Color, sizeF: Float, text: String, xT: Float, yT: Float)', 'description':'utils.LabelBuilder.LabelBuilder', 'location':'core/utils/-label-builder/-label-builder.html', 'searchKey':'LabelBuilder'},
{'name': 'fun createFont(color: Color, sizef: Float, fileFont: FileHandle): BitmapFont', 'description':'utils.createFont', 'location':'core/utils/create-font.html', 'searchKey':'createFont'},
{'name': 'fun heightPer(p: Float): Float', 'description':'utils.heightPer', 'location':'core/utils/height-per.html', 'searchKey':'heightPer'},
{'name': 'fun widthPer(p: Float): Float', 'description':'utils.widthPer', 'location':'core/utils/width-per.html', 'searchKey':'widthPer'},
{'name': 'fun worldHeightPer(v: Viewport, p: Float): Float', 'description':'utils.worldHeightPer', 'location':'core/utils/world-height-per.html', 'searchKey':'worldHeightPer'},
{'name': 'fun worldWidthPer(v: Viewport, p: Float): Float', 'description':'utils.worldWidthPer', 'location':'core/utils/world-width-per.html', 'searchKey':'worldWidthPer'}]
